apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertx
  namespace: learning01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vertx
  template:
    metadata:
      labels:
        app: vertx
    spec:
      containers:
        - name: vertx
          image: vertx-service:latest
          # Your Vert.x HTTP/WebSocket server listens on 8081 in the code
          ports:
            - containerPort: 8081
          # Gets KAFKA_USERNAME / KAFKA_PASSWORD (and others) from the same secret
          envFrom:
            - secretRef:
                name: app-credentials
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: vertx
  namespace: learning01
spec:
  type: ClusterIP
  selector:
    app: vertx
  ports:
    - port: 8080        # what other services/Ingress call
      targetPort: 8081  # actual port inside the Vert.x container