apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learning01-ingress
  namespace: learning01
spec:
  rules:
    - host: APP_HOST
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react
                port:
                  number: 80
    - host: API_HOST
      http:
        paths:
          - path: /spring/api
            pathType: Prefix
            backend:
              service:
                name: spring-api
                port:
                  number: 8080
    - host: VERTX_HOST
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: vertx
                port:
                  number: 8080   # Service â†’ pod:8081
          - path: /stream
            pathType: Prefix
            backend:
              service:
                name: vertx
                port:
                  number: 8080
