apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learning01-ingress
  namespace: learning01
spec:
  rules:
  - host: app.<VM-IP>.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-svc
            port:
              number: 80
  - host: api.10-0-2-15.nip.io
    http:
      paths:
      - path: /spring/api
        pathType: Prefix
        backend:
          service:
            name: spring-svc
            port:
              number: 8080