apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learning01-ingress
  namespace: learning01
spec:
  rules:
    - host: app.10.0.2.15.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react
                port:
                  number: 80

    - host: api.10.0.2.15.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-api
                port:
                  number: 8080

    - host: vertx.10.0.2.15.nip.io
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: vertx
                port:
                  number: 8080
          - path: /stream
            pathType: Prefix
            backend:
              service:
                name: vertx
                port:
                  number: 8080